### ISSUE TITLE
5.11.4 fails to build with ftxui-4.1.0

### ISSUE THREAD

**Issue by yurivict** [eclipse-ecal/ecal#1108]
### Problem Description

```
In file included from /wrkdirs/usr/ports/net/ecal/work/ecal-5.11.4/app/mon/mon_tui/src/main.cpp:29:
In file included from /wrkdirs/usr/ports/net/ecal/work/ecal-5.11.4/app/mon/mon_tui/src/tui/tui.hpp:31:
/wrkdirs/usr/ports/net/ecal/work/ecal-5.11.4/app/mon/mon_tui/src/tui/style_sheet.hpp:113:39: error: no member named 'Right' in 'ftxui::MenuOption'
    sheet.tab.direction = MenuOption::Right;
                          ~~~~~~~~~~~~^
/wrkdirs/usr/ports/net/ecal/work/ecal-5.11.4/app/mon/mon_tui/src/tui/style_sheet.hpp:212:39: error: no member named 'Right' in 'ftxui::MenuOption'
    sheet.tab.direction = MenuOption::Right;
                          ~~~~~~~~~~~~^
```

### How to reproduce

regular build

### How did you get eCAL?

Custom Build / Built from source

### Environment

- eCAL: 5.11.4
- OS: FreeBSD 13.2

**Comment by FlorianReimold** [comment]
Have you tried ftxui 4.0.0? https://github.com/ArthurSonzogni/FTXUI/releases/tag/v4.0.0
That is our currently supported version that we have linked as git submodule in the master branch. The 5.11.4 release is still on an older state of ftxui.

**Comment by KerstinKeller** [comment]
Apparently FTXUI 4.1.0 had a API breaking change from 4.0.0 -> 4.1.0. We'll see what can be done about it, but atm eCAL supports only ftui <= 4.0.0.

**Comment by FlorianReimold** [comment]
The FTXUI developer published a fixed release.
https://github.com/ArthurSonzogni/FTXUI/issues/649

**Comment by KerstinKeller** [comment]
@FlorianReimold should we update the submodule anyways (for master)?

**Comment by FlorianReimold** [comment]
Sure, why not. Currently we have linked 4.0.0.
