### PR TITLE
[python] Fix iterating over measurement which was broken by fe84826

### LINKED ISSUE #1748: Python API for measurement.__iter__() is broken
### Problem Description

When I run the following Python code, I would expect to iterate over the measurement channels. Instead, a `TypeError` is raised.

```python
    measurement = Measurement(str(measurement_path))
    for channel in measurement:
        for message in channel:
            print(message)
```

```
Traceback (most recent call last):
  File "/home/uidg4302/projects/cls_dspace/python/src/tools/analyze_acc.py", line 18, in <module>
    main()
  File "/home/uidg4302/python/cls_venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/uidg4302/python/cls_venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/uidg4302/python/cls_venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/uidg4302/python/cls_venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/uidg4302/projects/cls_dspace/python/src/tools/analyze_acc.py", line 12, in main
    for channel in measurement:
  File "/home/uidg4302/python/cls_venv/lib/python3.8/site-packages/ecal/measurement/measurement.py", line 215, in __iter__
    return Measurement.Iterator(self)
TypeError: __init__() missing 1 required positional argument: 'channel_type'
```

I think the `Measurement.__init__()` has a bug and is not using the constructor for `Measurement.Iterator` correctly.

Please see: https://github.com/eclipse-ecal/ecal/blob/fe848260f9bc08e10c860f0fdf60651f09df0735/lang/python/ecalhdf5/ecal/measurement/measurement.py#L215

and: https://github.com/eclipse-ecal/ecal/blob/fe848260f9bc08e10c860f0fdf60651f09df0735/lang/python/ecalhdf5/ecal/measurement/measurement.py#L190

### How to reproduce

See above how to reproduce the issue.

### How did you get eCAL?

Download from Release Page

### Environment

-eCAL: 5.12.6
-OS: Ubuntu 20.04
-Python: 3.8
-Compiler and CMake: not applicable

### eCAL System Information

_No response_

### PR DESCRIPTION
**Pull request by KerstinKeller**
### Description
When Binary Reading mode was introduced to the Python API, this broke the regular iteration over a measurement.
This PR fixes this.

### Related issues
Fixes #1748

### CODE REVIEW

**Review by hannemn — APPROVED** [review]
LGTM
